---
syntax: markdown
# -*- mode: markdown -*-
---

- `$@` : filename of the target (left of :)
- `$(@D)` : directory part of the target
- `$(@F)` : file part of the target

- `$<` : name of the first prerequisite (right of :)
- `$(<D)` : directory part of the first prerequisite
- `$(<F)` : file part of the first prerequisite

- `$^` : all prerequisites (right of :)
- `$(^D)` : directory part of the all prerequisites
- `$(^F)` : file part of the all prerequisites
